nuclei = {'Blue': {'colour': (0, 0, 255),
          'relations': {'Blue': {'attraction': -0.03, 'range': 148},
                        'Cyan': {'attraction': 0.27, 'range': 137},
                        'Green': {'attraction': -0.55, 'range': 98},
                        'Purple': {'attraction': 0.07, 'range': 133},
                        'Red': {'attraction': -0.49, 'range': 149},
                        'Yellow': {'attraction': 0.57, 'range': 147}}},
 'Green': {'colour': (0, 255, 0),
           'relations': {'Blue': {'attraction': 0.41, 'range': 76},
                        'Cyan': {'attraction': 0.27, 'range': 137},
                         'Green': {'attraction': 0.42, 'range': 111},
                         'Purple': {'attraction': 0.36, 'range': 86},
                         'Red': {'attraction': -0.15, 'range': 97},
                         'Yellow': {'attraction': -0.67, 'range': 120}}},
 'Purple': {'colour': (255, 0, 255),
            'relations': {'Blue': {'attraction': 0.13, 'range': 120},
                        'Cyan': {'attraction': 0.27, 'range': 137},
                          'Green': {'attraction': -0.81, 'range': 130},
                          'Purple': {'attraction': -0.5, 'range': 115},
                          'Red': {'attraction': 0.01, 'range': 132},
                          'Yellow': {'attraction': -0.98, 'range': 128}}},
 'Red': {'colour': (255, 0, 0),
         'relations': {'Blue': {'attraction': 0.58, 'range': 146},
                        'Cyan': {'attraction': 0.27, 'range': 137},
                       'Green': {'attraction': 0.95, 'range': 87},
                       'Purple': {'attraction': -0.4, 'range': 91},
                       'Red': {'attraction': -0.18, 'range': 118},
                       'Yellow': {'attraction': 0.62, 'range': 123}}},
 'Yellow': {'colour': (255, 255, 0),
            'relations': {'Blue': {'attraction': -0.51, 'range': 136},
                        'Cyan': {'attraction': 0.27, 'range': 137},
                          'Green': {'attraction': -0.46, 'range': 121},
                          'Purple': {'attraction': -0.45, 'range': 104},
                          'Red': {'attraction': -0.5, 'range': 150},
                          'Yellow': {'attraction': -0.18, 'range': 113}}},
 'Cyan': {'colour': (0, 255, 255),
          'relations': {'Blue': {'attraction': -0.67, 'range': 112},
                        'Cyan': {'attraction': -0.42, 'range': 116},
                        'Green': {'attraction': -0.21, 'range': 77},
                        'Purple': {'attraction': 0.17, 'range': 125},
                        'Red': {'attraction': 0.2, 'range': 132},
                        'Yellow': {'attraction': 0.56, 'range': 133}}}}
runners = {'Blue': {'colour': (0, 0, 255),
          'relations': {'Blue': {'attraction': -0.3, 'range': 148},
                        'Cyan': {'attraction': 0.27, 'range': 137},
                        'Green': {'attraction': 0.18, 'range': 80},
                        'Purple': {'attraction': -0.66, 'range': 88},
                        'Red': {'attraction': -0.69, 'range': 145},
                        'Yellow': {'attraction': -0.58, 'range': 118}}},
 'Cyan': {'colour': (0, 255, 255),
          'relations': {'Blue': {'attraction': -1, 'range': 112},
                        'Cyan': {'attraction': -0.42, 'range': 116},
                        'Green': {'attraction': -0.21, 'range': 77},
                        'Purple': {'attraction': 0.17, 'range': 125},
                        'Red': {'attraction': 0.2, 'range': 132},
                        'Yellow': {'attraction': 0.56, 'range': 133}}},
 'Green': {'colour': (0, 255, 0),
           'relations': {'Blue': {'attraction': 0.95, 'range': 128},
                         'Cyan': {'attraction': -0.25, 'range': 126},
                         'Green': {'attraction': -0.35, 'range': 83},
                         'Purple': {'attraction': -0.69, 'range': 84},
                         'Red': {'attraction': -0.67, 'range': 113},
                         'Yellow': {'attraction': -0.67, 'range': 133}}},
 'Purple': {'colour': (255, 0, 255),
            'relations': {'Blue': {'attraction': 0.37, 'range': 134},
                          'Cyan': {'attraction': -0.37, 'range': 132},
                          'Green': {'attraction': 0.38, 'range': 86},
                          'Purple': {'attraction': 0.43, 'range': 140},
                          'Red': {'attraction': -0.22, 'range': 140},
                          'Yellow': {'attraction': -0.69, 'range': 130}}},
 'Red': {'colour': (255, 0, 0),
         'relations': {'Blue': {'attraction': -0.15, 'range': 122},
                       'Cyan': {'attraction': 0.02, 'range': 146},
                       'Green': {'attraction': -1.0, 'range': 121},
                       'Purple': {'attraction': -0.1, 'range': 81},
                       'Red': {'attraction': -0.79, 'range': 109},
                       'Yellow': {'attraction': 0.65, 'range': 131}}},
 'Yellow': {'colour': (255, 255, 0),
            'relations': {'Blue': {'attraction': 0.45, 'range': 110},
                          'Cyan': {'attraction': 0.12, 'range': 140},
                          'Green': {'attraction': 0.16, 'range': 79},
                          'Purple': {'attraction': 0.87, 'range': 146},
                          'Red': {'attraction': 0.41, 'range': 135},
                          'Yellow': {'attraction': 0.52, 'range': 80}}}}
clumps = {'Blue': {'colour': (0, 0, 255),
          'relations': {'Blue': {'attraction': 0.23, 'range': 150},
                        'Cyan': {'attraction': 0.61, 'range': 115},
                        'Green': {'attraction': 0.56, 'range': 120},
                        'Purple': {'attraction': 0.64, 'range': 111},
                        'Red': {'attraction': 0.47, 'range': 88},
                        'Yellow': {'attraction': 0.99, 'range': 84}}},
 'Cyan': {'colour': (0, 255, 255),
          'relations': {'Blue': {'attraction': -0.18, 'range': 112},
                        'Cyan': {'attraction': 0.26, 'range': 144},
                        'Green': {'attraction': 0.36, 'range': 142},
                        'Purple': {'attraction': -0.72, 'range': 95},
                        'Red': {'attraction': -0.54, 'range': 145},
                        'Yellow': {'attraction': 0.2, 'range': 114}}},
 'Green': {'colour': (0, 255, 0),
           'relations': {'Blue': {'attraction': 0.86, 'range': 94},
                         'Cyan': {'attraction': 0.57, 'range': 109},
                         'Green': {'attraction': -0.84, 'range': 121},
                         'Purple': {'attraction': 0.93, 'range': 125},
                         'Red': {'attraction': -0.26, 'range': 124},
                         'Yellow': {'attraction': 0.41, 'range': 129}}},
 'Purple': {'colour': (255, 0, 255),
            'relations': {'Blue': {'attraction': 0.98, 'range': 78},
                          'Cyan': {'attraction': -0.21, 'range': 96},
                          'Green': {'attraction': 0.88, 'range': 146},
                          'Purple': {'attraction': 0.93, 'range': 112},
                          'Red': {'attraction': -0.96, 'range': 81},
                          'Yellow': {'attraction': -0.82, 'range': 129}}},
 'Red': {'colour': (255, 0, 0),
         'relations': {'Blue': {'attraction': 0.6, 'range': 150},
                       'Cyan': {'attraction': -0.43, 'range': 122},
                       'Green': {'attraction': 0.63, 'range': 103},
                       'Purple': {'attraction': 0.13, 'range': 99},
                       'Red': {'attraction': 0.44, 'range': 78},
                       'Yellow': {'attraction': 0.12, 'range': 95}}},
 'Yellow': {'colour': (255, 255, 0),
            'relations': {'Blue': {'attraction': -0.25, 'range': 137},
                          'Cyan': {'attraction': -0.56, 'range': 117},
                          'Green': {'attraction': 0.8, 'range': 87},
                          'Purple': {'attraction': 0.96, 'range': 110},
                          'Red': {'attraction': -0.22, 'range': 88},
                          'Yellow': {'attraction': 0.64, 'range': 147}}}}